/*
 * This source file was generated by the Gradle 'init' task
 */
package tron.grpc.test;

import io.grpc.ClientInterceptor;
import java.util.ArrayList;
import org.tron.trident.core.ApiWrapper;
import org.tron.trident.core.key.KeyPair;


public class App {
    public static void main(String[] args) { // Main method definition
        KeyPair keyPair = KeyPair.generate();

        String hostAndPort = "provider-url.com:443";
        // String hostAndPort = "localhost:8081";

        // Create a ClientInterceptor to inject the "x-token" header
        ClientInterceptor interceptor = new HeaderClientInterceptor();

        ArrayList<ClientInterceptor> interceptorList = new ArrayList<>();
        interceptorList.add(interceptor);

        //Initialize with special grpc endpoint
        ApiWrapper client = new ApiWrapper(hostAndPort, hostAndPort, keyPair.toPrivateKey(), interceptorList);
        long balance = client.getAccountBalance("TT2T17KZhoDu47i2E4FWxfG79zdkEWkU9N"); // balance in SUN (1 TRX = 1,000,000 SUN)
        System.out.println("Balance: " + balance / 1_000_000.0 + " TRX"); // Print the balance
    }
}
